export class Sector4IPPU{
  public city: string ;
  public inventoryPeriod: string;
  public subSector: string ;
  public scope: string ;
  public userName: string ;
  public clinker: number;
  public clinkerUnit: string;
  public lime: number;
  public limeUnit: string;
  public glass: number;
  public glassUnit: string;
  public ammonia: number;
  public ammoniaUnit: string;
  public nitricAcid: number;
  public nitricAcidUnit: string;
  public adipicAcid: number;
  public adipicAcidUnit: string;
  public othersAcid: number;
  public othersAcidUnit: string;
  public carbide: number;
  public carbideUnit: string;
  public titanium: number;
  public titaniumUnit: string;
  public soda: number;
  public sodaUnit: string;
  public metallurgical: number;
  public metallurgicalUnit: string;
  public iron: number;
  public ironUnit: string;
  public ferroalloy: number;
  public ferroalloyUnit: string;
  public aluminum: number;
  public aluminumUnit: string;
  public magnesium: number;
  public magnesiumUnit: string;
  public leadProduction: number;
  public leadUnit: string;
  public zinc: number;
  public zincUnit: string;
  public other: number;
  public otherUnit: string;
  public otherDescription: string;
  public lubricants: number;
  public lubricantsUnit: string;
  public parafin: number;
  public parafinUnit: string;
  public petroleum: number;
  public petroleumUnit: string;
  public aromatics: number;
  public aromaticsUnit: string;
  public fluids: number;
  public fluidsUnit: string;
  public pfc: number;
  public pfcUnit: string;
  public hfc: number;
  public hfcUnit: string;
  public other2: number;
  public other2Unit: string;
  public other2Description: string;
  
    
  constructor() {
    this.city = null;
    this.inventoryPeriod = null;
    this.subSector = null;
    this.scope = null;
    this.userName = null;
    this.clinker= null;
    this.clinkerUnit= null;
    this.lime= null;
    this.limeUnit= null;
    this.glass= null;
    this.glassUnit= null;
    this.ammonia= null;
    this.ammoniaUnit= null;
    this.nitricAcid= null;
    this.nitricAcidUnit= null;
    this.adipicAcid= null;
    this.adipicAcidUnit= null;
    this.othersAcid= null;
    this.othersAcidUnit= null;
    this.carbide= null;
    this.carbideUnit= null;
    this.titanium= null;
    this.titaniumUnit= null;
    this.soda= null;
    this.sodaUnit= null;
    this.metallurgical= null;
    this.metallurgicalUnit= null;
    this.iron= null;
    this.ironUnit= null;
    this.ferroalloy= null;
    this.ferroalloyUnit= null;
    this.aluminum= null;
    this.aluminumUnit= null;
    this.magnesium= null;
    this.magnesiumUnit= null;
    this.leadProduction= null;
    this.leadUnit= null;
    this.zinc= null;
    this.zincUnit= null;
    this.other= null;
    this.otherUnit= null;
    this.otherDescription= null;
    this.lubricants= null;
    this.lubricantsUnit= null;
    this.parafin= null;
    this.parafinUnit= null;
    this.petroleum= null;
    this.petroleumUnit= null;
    this.aromatics= null;
    this.aromaticsUnit= null;
    this.fluids= null;
    this.fluidsUnit= null;
    this.pfc= null;
    this.pfcUnit= null;
    this.hfc= null;
    this.hfcUnit= null;
    this.other2= null;
    this.other2Unit= null;
    this.other2Description= null;    
  }
}